"""initial schema

Revision ID: 1494cda2809c
Revises: 
Create Date: 2026-09-19 10:42:39.563238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1494cda2809c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=False),
    sa.Column('has_seen_intro', sa.Boolean(), nullable=False),
    sa.Column('dismissed_hints', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('websites',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=False)
    op.create_index(op.f('ix_websites_owner_id'), 'websites', ['owner_id'], unique=False)
    op.create_table('audits',
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CRAWLING', 'ANALYZING', 'COMPLETED', 'FAILED', name='audit_status'), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('pages_limit', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_website_id'), 'audits', ['website_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'OPPORTUNITY', name='issue_severity'), nullable=False),
    sa.Column('category', sa.Enum('TECHNICAL', 'ON_PAGE', 'CONTENT', 'INTERNAL_LINKING', 'INDEXABILITY', name='issue_category'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('affected_page_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('affected_page_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_audit_id'), 'opportunities', ['audit_id'], unique=False)
    op.create_index(op.f('ix_opportunities_issue_type'), 'opportunities', ['issue_type'], unique=False)
    op.create_table('pages',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('crawl_depth', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('redirect_count', sa.Integer(), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('meta_description', sa.String(length=2000), nullable=True),
    sa.Column('h1s', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('h2s', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('internal_link_count', sa.Integer(), nullable=False),
    sa.Column('external_link_count', sa.Integer(), nullable=False),
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('robots_meta', sa.String(length=255), nullable=True),
    sa.Column('fetch_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_audit_id'), 'pages', ['audit_id'], unique=False)
    op.create_table('links',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('source_page_id', sa.UUID(), nullable=False),
    sa.Column('destination_page_id', sa.UUID(), nullable=True),
    sa.Column('destination_url', sa.String(length=2048), nullable=False),
    sa.Column('anchor_text', sa.String(length=500), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_audit_id'), 'links', ['audit_id'], unique=False)
    op.create_index(op.f('ix_links_destination_page_id'), 'links', ['destination_page_id'], unique=False)
    op.create_index(op.f('ix_links_source_page_id'), 'links', ['source_page_id'], unique=False)
    op.create_table('seo_issues',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'OPPORTUNITY', name='issue_severity'), nullable=False),
    sa.Column('category', sa.Enum('TECHNICAL', 'ON_PAGE', 'CONTENT', 'INTERNAL_LINKING', 'INDEXABILITY', name='issue_category'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_issues_audit_id'), 'seo_issues', ['audit_id'], unique=False)
    op.create_index(op.f('ix_seo_issues_issue_type'), 'seo_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_seo_issues_page_id'), 'seo_issues', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_issues_page_id'), table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_issue_type'), table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_audit_id'), table_name='seo_issues')
    op.drop_table('seo_issues')
    op.drop_index(op.f('ix_links_source_page_id'), table_name='links')
    op.drop_index(op.f('ix_links_destination_page_id'), table_name='links')
    op.drop_index(op.f('ix_links_audit_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_pages_audit_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_opportunities_issue_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_audit_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_audits_website_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_websites_owner_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
